import { Poppins } from "next/font/google"; // Import Poppins
import "./globals.css";

// Configure Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Specify desired weights
  variable: "--font-poppins", // Define a CSS variable for Poppins
});

export const metadata = {
  title: "ChurchPlus Partnership Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply Poppins font using its CSS variable */}
      <body className={`${poppins.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
